#############################################################################################
# Inputs
# Configuration required
#############################################################################################
source: local                         # [local|sra] whether RNAseq data is stored locally or should be fetched from SRA
rawInputDir: /data/gpfs/assoc/pgl/data/iceplant/rna-seq/USDS/bam # (path) path to local RNAseq data directory (source=local)
sra_dir: placeholder                  # (path) path to sra directory... see README (source=sra)

libraryType: SINGLE                   # [PAIRED|SINGLE] RNAseq library type
PAIR_LIST: [_1, _2]                   # Unique suffixes used for paired-end read files (libraryType=PAIRED)

genomeDir: /data/gpfs/assoc/pgl/data/iceplant/rna-seq/USDS/PGRP_Snakemake/ref
GTF_name: /data/gpfs/assoc/pgl/data/iceplant/rna-seq/USDS/PGRP_Snakemake/ref/genome.gtf
ref: [SA, SAindex, exonGeTrInfo.tab]  # Files to check for successful STAR reference preparation

readCounting: [RSEM]                  # (list) Read counting methods to use. Options are (RSEM|featureCounts|HTseq|TPMcalculator)
RSEM_prepared_genome: /data/gpfs/assoc/pgl/data/iceplant/rna-seq/USDS/PGRP_Snakemake/ref

runDEG: no                           # [yes|no] Whether to perform DEG analysis using Trinity
                                      # NOTE: DEG anlaysis will be perfromed with all selected read counting methods except TPMcalculator
sample_contrast: placeholder          # (path) DEG contrasts to perform. If not included, all contrasts are calculated
rep_relations: replication_relationship.txt # (path) Treatment/Replicate relationships file between. Created from RunsbyExperiment.tsv by default.

#############################################################################################
# Threads 
# Configuration optional
#############################################################################################

threads:
  importRaw: 2
  fetchSRA: 2
  convertSRAtoFastq: 8
  fastqc_raw: 2
  trim: 16
  align: 16
  calculateRSEMExpression: 16
  merge: 16
  featureCount: 16
  HTseq: 16
  normalizeFeatureCounts: 2
  normalizeHTseq: 2
  TPMCalculator: 8
  mergeTPMCalculator: 2
  DEG_featureCounts: 8
  DEG_HTseq: 8
  DEG_RSEM: 8

#############################################################################################
# Cluster
# Configuration required
#############################################################################################

__default__:
  account: cpu-s1-pgl-0    # Provide your slurm account
  partition: cpu-s1-pgl-0  # Provide your slurm partition
  memory: 8g
  name: "{rule}.{wildcards}"
  ncpus: 2
  nodes: 1
  time: 7-0:00:00
  output: output/logs/{rule}.{wildcards}.out
  error: output/logs/{rule}.{wildcards}.err
fetchSRA:
  ncpus: 2
  memory: 8g
importRaw_paired:
  ncpus: 2
  memory: 8g
importRaw_single:
  ncpus: 2
  memory: 8g
convertSRAtoFastq_SINGLE:
  ncpus: 8
  memory: 64g
convertSRAtoFastq_PAIRED:
  ncpus: 8
  memory: 64g
fastqc_raw_SINGLE:
  ncpus: 2
  memory: 8g
fastqc_raw_PAIRED:
  ncpus: 2
  memory: 8g
fastqc_raw:
  ncpus: 2
  memory: 8g
trim_SINGLE:
  ncpus: 16
  memory: 64g
trim_PAIRED:
  ncpus: 16
  memory: 64g
fastqc_trim_SINGLE:
  ncpus: 2
  memory: 8g
fastqc_trim_PAIRED:
  ncpus: 2
  memory: 8g
align_SINGLE:
  ncpus: 16
  memory: 64g
align_PAIRED:
  ncpus: 16
  memory: 64g
alignRSEM_PAIRED:
  ncpus: 16
  memory: 64g
alignRSEM_SINGLE:
  ncpus: 16
  memory: 64g
calculateRSEMExpression_SINGLE:
  ncpus: 16
  memory: 64g
calculateRSEMExpression_PAIRED:
  ncpus: 16
  memory: 64g
mergeSTAR:
  ncpus: 16
  memory: 64g
mergeRSEM:
  ncpus: 16
  memory: 64g
featureCounts:
  ncpus: 16
  memory: 64g
HTseq:
  ncpus: 16
  memory: 64g
normalizeFeatureCounts:
  ncpus: 2
  memory: 8g
normalizeHTseq:
  ncpus: 2
  memory: 8g
TPMCalculator:
  ncpus: 8
  memory: 64g
mergeTPMCalculator:
  ncpus: 2
  memory: 8g
DEG_featureCounts:
  ncpus: 8
  memory: 64g
DEG_HTseq:
  ncpus: 8
  memory: 64g
DEG_RSEM:
  ncpus: 8
  memory: 64g
summarize:
  ncpus: 2
  memory: 8g
summarizeRSEM:
  ncpus: 2
  memory: 8g
